#! /bin/sh
### BEGIN INIT INFO
# Provides:          rvi
# Required-Start:    $syslog $time $remote_fs
# Required-Stop:     $syslog $time $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Remote Vehicle Interaction (RVI) Server
# Description:       Debian init script for the rvi server 
### END INIT INFO
#
# Author:	Rudolf Streif (rstreif@jaguarlandrover.com)
#

PATH=/bin:/usr/bin:/sbin:/usr/sbin
DAEMON_PATH=/var/www/rvibackend/server
DAEMON=rviserver.py
PIDFILE=/var/run/rviserver.pid

test -e $DAEMON_PATH/$DAEMON || exit 0

. /lib/lsb/init-functions

case "$1" in
  start)
	log_daemon_msg "Starting Remote Vehicle Interaction (RVI) Server" "rvi"
        cd $DAEMON_PATH
	/usr/bin/python $DAEMON st $PIDFILE
	log_end_msg $?
    ;;
  stop)
	log_daemon_msg "Stopping Remote Vehicle Interaction (RVI) Server" "rvi"
        cd $DAEMON_PATH
	/usr/bin/python $DAEMON sp $PIDFILE
	log_end_msg $?
    ;;
  force-reload|restart)
    $0 stop
    $0 start
    ;;
  status)
    status_of_proc -p $PIDFILE $DAEMON atd && exit 0 || exit $?
    ;;
  *)
    echo "Usage: /etc/init.d/rvi {start|stop|restart|force-reload|status}"
    exit 1
    ;;
esac

exit 0
